DROP TABLE IF EXISTS tab_user;
CREATE TABLE tab_user (
  userId INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(30) NOT NULL,
  password VARCHAR(30) NOT NULL,
  totalLogins INT DEFAULT 0 NOT NULL,
  totalFails INT DEFAULT 0 NOT NULL,
  isBlocked BOOLEAN DEFAULT FALSE NOT NULL
);

DROP TABLE IF EXISTS tab_history;
CREATE TABLE tab_history (
  historyId INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(30) NOT NULL,
  date DATE NOT NULL,
);
COMMIT;